service: minecraft-service
provider:
  name: aws
package:
  individually: true
functions:
  backup:
    handler: src/backup/handler.backup
    package:
      exclude:
        - ./**
      include: 
        - src/backup/handler.py
      tags:
        version: 1.0.0
