service: minecraft-service
provider:
  name: aws
  runtime: python3.6
  region: us-east-1
package:
  individually: true
functions:
  backup:
    handler: src/backup/handler.backup
    package:
      exclude:
        - ./**
      include: 
        - src/backup/handler.py
      tags:
        version: 1.0.0
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - ssm:GetParameter
        Resource: 
          - "arn:aws:ssm:*:*:parameter/PRIVATE_KEY"
plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    slimPatterns:
      - "*.egg-info*"
