service: minecraft-service
provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  stage: prod
  environment:
    SERVICE_NAME: ${self:service}
package:
  individually: true
functions:
  hello:
    handler: src/backup/handler.handler
    package:
      exclude:
        - ./**
      include: 
        - src/backup/handler.py
    events:
      - http:
          path: backup
          method: get
          cors: true
          