version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: v1-pip-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Dependencies
          command: make venv
      - save_cache:
          key: v1-pip-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Lint Code
          command: make lint
  deploy:
    docker:
      - image: bckr/lambda-deploy-tools:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Dependencies
          command: make venv
      - run: 
          name: Build
          command: make build
      - run:
          name: Package
          command: make package
      - run:
          name: Deploy
          command: |
            terraform init terraform/output/
            terraform plan terraform/output/ # TODO: switch to apply --auto-approve
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - deploy:
          context: dockerhub
          requires:
            - build
          filters:
            branches:
              # only: master # Swap back after
              only: /.*/
