version: 2
jobs:
  build:
    docker:
      - image: bckr/lambda-tools:latest
    steps:
      - checkout
      - restore_cache:
          key: v3-pip-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Dependencies
          command: make venv
      - save_cache:
          key: v3-pip-{{ checksum "requirements-dev.txt" }}
          paths:
            - "/root/project/venv"
      - run:
          name: Lint Code
          command: make lint
  deploy:
    docker:
      - image: bckr/lambda-tools:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: v3-pip-{{ checksum "requirements-dev.txt" }}
      - run: 
          name: Build
          command: make build
      - run:
          name: Package
          command: make package
      - run:
          name: Deploy
          command: make plan # TODO: switch to deploy
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - deploy:
          context: dockerhub
          requires:
            - build
          filters:
            branches:
              only: /.*/
