version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: v1-pip-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Dependencies
          command: make venv
      - save_cache:
          key: v1-pip-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Lint Code
          command: make lint
  # deploy:
  #   docker:
  #     - image: circleci/node:8.10
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-node-
  #     - run:
  #         name: Install Serverless CLI
  #         command: sudo npm i -g serverless
  #     - save_cache:
  #         key: v1-node-
  #         paths:
  #           - /usr/local/lib/node_modules/
  #     - run:
  #         name: Deploy AWS Lambda
  #         command: severless deploy 
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
