version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s [%(filename)s] %(levelname)-s: %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
loggers:
    <module>:
        level: INFO
        handlers: [console]
        propogate: no
root:
    level: INFO
    handlers: [console]
